{
  "name": "catch-async-wrapper-express",
  "version": "2.0.0",
  "description": "middleware for handling exceptions inside of async express routes and passing them to your express or custom error handlers",
  "main": "./dist/index.js",
  "type": "commonjs",
  "types": "./@types/index.d.ts",
  "scripts": {
    "build": "tsc .",
    "test": "tsx ./tests/index.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/samislam/catch-async-wrapper-express"
  },
  "keywords": [
    "catchasync",
    "express-async-handler",
    "express-catch-async",
    "express-async-middleware",
    "express",
    "middleware",
    "trycatch-wrapper",
    "trycatchwrapper",
    "express-try-catch",
    "express-trycatch"
  ],
  "author": "Islam Yamor",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/samislam/catchasync/issues"
  },
  "homepage": "https://github.com/samislam/catchasync#readme",
  "dependencies": {
    "@samislam/checktypes": "^1.0.1",
    "@samislam/log": "^1.1.4",
    "express": "^4.18.2",
    "typescript": "^5.3.3"
  },
  "devDependencies": {
    "@types/express": "^4.17.21",
    "@types/node": "^20.10.4",
    "tsx": "^4.6.2"
  }
}
